server:
  port: 8000

eureka:
  client:
    register-with-eureka: true  # eureka ??
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: String Cload GateWay GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
#          uri: http://127.0.0.1:8081/ ip:port
          uri: lb://MY-FIRST-SERVICE # ??? ?
          predicates:
            - Path=/first-service/**
          filters:
#            - AddRequestHeader=first-request, first-request-header2 // yml???? ???? ??
#            - AddResponseHeader=first-reponse, first-response-header2
            - CustomFilter
        - id: seconde-service
#          uri: http://127.0.0.1:8082/
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2
            - name: CustomFilter
            - name: LoggerFilter # args ??? ??? name?? ?????
              args:
                baseMessage: Hi, There. This is secode-service
                preLogger: true
                postLogger: true



